context:
  version: "2.6.0"

package:
  name: ivy
  version: ${{ version }}

source:
  url: https://dlcdn.apache.org//ant/ivy/${{ version }}/apache-ivy-${{ version }}-src.tar.gz
  sha256: 7a1c4056af114ef7ed61f3665a614ce7085a442d5712a85a5bbebf84b217d29c

build:
  number: 0
  noarch: generic

requirements:
  host:
    - ant
    - maven
    - openjdk =11
    - sed
  run:
    - openjdk

tests:
  - script:
      - ivy -version

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Agile dependency manager
  homepage: https://ant.apache.org/ivy

extra:
  recipe-maintainers:
    - danielnachun
